package com.acmebank.banking.account.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@Schema(
        name = "Transaction Detail DTO",
        description = "Schema to hold Transaction Detail information"
)
public class TransactionDetailDto {

    @Schema(
            description = "Transaction Number generated by UUID and prefix code", example = "TXN_94DD9CFB69C24A7588B3589BD0E57647"
    )
    private String txnNo;
    @Schema(
            description = "Sender Acc No", example = "12345678"
    )
    private Long senderAccNo;

    @Schema(
            description = "Receiver Acc No", example = "88888888"
    )
    private Long receiverAccNo;

    @Schema(
            description = "Sender Acc Currency Code", example = "HKD"
    )
    private String currencyCode;

    @Schema(
            description = "Transaction Amount", example = "100.00"
    )
    private BigDecimal amount;

    @Schema(
            description = "Transaction timestamp", example = "2024-06-27T14:50:44.1266962"
    )
    private LocalDateTime transferDt;

}
